### ISSUE TITLE
Token BInding Type is Contextual

### ISSUE THREAD

**Issue by Andrei-Popov** [TokenBinding/Internet-Drafts#12]
Token Binding ID includes tokenbinding_type field to indicate whether this is a Provided or Referred binding.

In the federation scenario, the client proves possession of the same Krp to the RP (as Provided binding) and to the IDP (as Referred binding). If the IDP includes the Referred Token Binding ID in the token, the RP cannot directly compare it with the Provided Token Binding ID established with the client, because the first byte of the ID (tokenbinding_type) will be different.

We should provide guidance on this in draft-ietf-tokbind-https to avoid confusion.

**Comment by balfanz** [comment]
Good catch. I had written the spec as if the Token Binding ID _is_ the public key. I changed the wording in f00f1cf165487d9c495b6a0be04ea4b5c016717b.
