### ISSUE TITLE
Other redirect status codes

### ISSUE THREAD

**Issue by annevk** [TokenBinding/Internet-Drafts#13]
http://xml2rfc.ietf.org/cgi-bin/xml2rfc.cgi?modeAsFormat=html/ascii&url=https://raw.githubusercontent.com/TokenBinding/Internet-Drafts/master/draft-ietf-tokbind-https-01.xml#rfc.section.3.3

> his header has only meaning if the HTTP status code is 302 or 301,

Why exclude support for 303, 307, and 308?

**Comment by balfanz** [comment]
Fixed in d3325e4.
