### ISSUE TITLE
Please don't extend XMLHttpRequest

### ISSUE THREAD

**Issue by annevk** [TokenBinding/Internet-Drafts#2]
We should really only be extending `fetch()` at this point.

**Comment by annevk** [comment]
And furthermore, none of these documents should actually do that, they should provide hooks for the API layer.

**Comment by annevk** [comment]
Note that there is a number of integration details we need to figure out:

1) Is it set at the API layer similar to a custom header? (Will be exposed to service workers, requires a CORS preflight.)

2) Is it set at the network layer based on a new flag to fetch? (Which APIs can set this flag? Should we expose it on `Request` somehow?)

**Comment by balfanz** [comment]
I removed the section on HttpXmlRequest (af5f6adb88a9cf1b50c2a71cdb6d004c166dee2f). Let's define those things over at the W3C.
