### ISSUE TITLE
TBPROTO: Add more info about the intended use of Referred bindings

### ISSUE THREAD

**Issue by equalsJeffH** [TokenBinding/Internet-Drafts#21]
per various discussions with OAuth folk at IETF-95, it appears there will be a forthcoming OAuth Internet-Draft making use of Token Binding Protocol and referred_token_binding TBtype.  Thus, we will retain referred_token_binding TBtype in TBPROTO (-tokbind-protocol) and update the relevant spec prose to hopefully make its semantics and use more clear.

**Comment by Andrei-Popov** [comment]
Merged.
