### ISSUE TITLE
HTTPSTB: be more explicit about multi-hop binding (RP->IDP1->IDP2->IDP1->RP)

### ISSUE THREAD

**Issue by equalsJeffH** [TokenBinding/Internet-Drafts#23]
HTTPSTB: be more explicit about multi-hop binding (RP->IDP1->IDP2->IDP1->RP)

**Comment by balfanz** [comment]
Hi Jeff - suggestions what this should look like in the spec? Since we [convinced ourselves](https://mailarchive.ietf.org/arch/msg/unbearable/undP0OsWJVxl7VtAC_61-VRZ540) that a single referred token binding suffices for these scenario, how should this be addressed in the spec?

**Comment by equalsJeffH** [comment]
there is a draft for resolving this in PR #47 -- WDYT?

[ (old,closed) issue #6 is also relevant to this issue it seems ]

**Comment by equalsJeffH** [comment]
Also, if a figure would be helpful, I can revamp ["figure 1" from the email threads](https://www.ietf.org/mail-archive/web/unbearable/current/msg00393.html) to illustrate this scenario and we could include it as an appendix, say.
