### ISSUE TITLE
HTTPSTB: explain why TB IDs are combined in one message, rather than sent in separate headers

### ISSUE THREAD

**Issue by equalsJeffH** [TokenBinding/Internet-Drafts#26]
HTTPSTB: explain why TB IDs are combined in one message, rather than sent in separate headers

**Comment by equalsJeffH** [comment]
See also..
https://www.ietf.org/mail-archive/web/unbearable/current/msg00493.html

From:  Unbearable unbearable-bounces@ietf.org on behalf of Andrei Popov Andrei.Popov@microsoft.com
Date:  Wednesday, April 6, 2016 at 11:38 AM
To:  Tokbind WG unbearable@ietf.org
Subject:  [Unbearable] TB APIs in (ASP).NET

At the meeting on Monday, there were a number of questions about platform support for TB and the APIs available to implementers.
Here are some links to (ASP).NET TB API documentation:

ASP.Net:
http://referencesource.microsoft.com/#System.Web/ITlsTokenBindingInfo.cs,4a5e5668f5c31170>

.NET code sample (see under “Networking enhancements”):
https://blogs.msdn.microsoft.com/dotnet/2015/11/30/net-framework-4-6-1-is-now-available/

.NET TokenBinding class:
https://msdn.microsoft.com/en-us/library/system.security.authentication.extendedprotection.tokenbinding(v=vs.110).aspx

Native TB library API, for those who don’t believe in garbage collectors:
https://msdn.microsoft.com/en-us/library/windows/desktop/mt269464(v=vs.85).aspx

Happy coding!
Cheers,
Andrei

**Comment by balfanz** [comment]
Seems like a pretty arbitrary decision to me - if we had them in separate headers, would we also have to write why they're in separate headers, not in one message? Does it matter?

**Comment by Andrei-Popov** [comment]
Either way would work; I believe that combining TBs in one message, in one header helps decouple HTTP code and TB code, but some might not agree. In any case, I don't believe we need to explain this design choice.

**Comment by equalsJeffH** [comment]
OK, this issue stemmed from Brian Campbell @b---c, and as I recall he has not pushed back on not adding such language, plus there is lack of interest as expressed by other co-editors above, and we are nearing the end of WGLC, so am closing this.
