### ISSUE TITLE
HTTPSTB: make it URL-safe base64

### ISSUE THREAD

**Issue by equalsJeffH** [TokenBinding/Internet-Drafts#27]
HTTPSTB: make it URL-safe base64

**Comment by b---c** [comment]
Current text in section 2 has "web-safe Base64-encoding" which many people will likely understand but is probably a bit too colloquial for an RFC. I might suggest something like the following, which borrows language from existing RFCs (like 7515) that also use a URL-safe base64 encoding.

> The header field name is "Sec-Token-Binding" and its value, EncodedTokenBindingMessage, is a web-safe Base64-encoding of the TokenBindingMessage defined in the TokenBindingProtocol [TBPROTO] using the URL- and filename-safe character set defined in Section 5 of RFC 4648 [RFC4648], with all trailing pad characters '=' omitted and without the inclusion of any line breaks, whitespace, or other additional characters.

**Comment by Andrei-Popov** [comment]
Done in HTTPSTB-04.
