### ISSUE TITLE
ALPN use

### ISSUE THREAD

**Issue by martinthomson** [TokenBinding/Internet-Drafts#3]
This really isn't something that is suited to ALPN.  If anything exists at the TLS layer, this is far better suited to an extension.  In many respects this is something that can be handled by client authentication even, though I think that the basic idea is to make this supplementary (or maybe just orthogonal) to client authentication.

The suggestion that was made at the last meeting was to look at using the signature_algorithms extension as the basis of determining what the server is capable of handling.  Then it only needs a (confidentiality-protected) message (a new handshake message perhaps) to carry the binding information.

**Comment by TokenBinding** [comment]
> This really isn't something that is suited to ALPN. If anything exists at the TLS layer, this is far better suited to an extension.
> What we need is to be able to negotiate the use of Token Binding, and the Token Binding key parameters, without introducing round-trips. I would not object to the idea of using a new TLS extension for this.
> 
> In many respects this is something that can be handled by client authentication even, though I think that the basic idea is to make this supplementary (or maybe just orthogonal) to client authentication.
> Correct, Token Binding is not authentication. Token Binding protects the tokens that are the result of authentication.
> 
> The suggestion that was made at the last meeting was to look at using the signature_algorithms extension as the basis of determining what the server is capable of handling.
> Unfortunately, this won't work: the set of algorithms available for TLS is not necessarily the same as the set of algorithms available for Token Binding. E.g. a client's TLS stack probably supports ECDSA, but the client's TPM may only support RSA. In this example, the client can't have a hardware-bound token with ECDSA. I believe we need a separate negotiation of Token Binding key parameters.

**Comment by annevk** [comment]
Wait, TokenBinding is a user, not an organization? You might want to fix that.

**Comment by Andrei-Popov** [comment]
Fixed! Learning github as I go...

**Comment by Andrei-Popov** [comment]
Per WG feedback, added TBNEGO I-D which specifies a TLS extension for TB negotiation.
