### ISSUE TITLE
HTTPSTB: discuss scoping of token binding keys earlier in the document 

### ISSUE THREAD

**Issue by b---c** [TokenBinding/Internet-Drafts#33]
As of draft-ietf-tokbind-https-03 in the Privacy Considerations [Section 5.1 Scoping of Token Binding Keys](https://tools.ietf.org/html/draft-ietf-tokbind-https-03#section-5.1) is the first real mention that token binding keys/ids should be scoped to public suffix + 1. Though the first sentence in 3.1 hints at it, it's not defined until later.

The scope of where TB keys are sent is a pretty fundamental part of HTTPSTB and, as such, I believe should be defined/discussed in Section 2 along with the Sec-Token-Binding header that the scoping applies to. The Privacy Considerations are still good considerations but then could refer back to the scoping definition in Sec 2 rather than being the definition. 

Public suffix + 1 makes sense as the scope for browser user agents but is maybe overly restrictive/prescriptive for some other HTTPS cases. OAuth access tokens come to mind, although it's still up in the air at this point how exactly OAuth will leverage TB, but there's potently a case for an OAuth client acting as an HTTPS client to want to have an token bound access token that can be used at multiple resource servers, which might be on different hosts/domains. The privacy concerns that arise from that situation are already there because the access token is correlatable so allowing the scope of the TB key to do the same doesn't make things any worse. It's the same from a privacy perspective,  just more secure. Having HTTPSTB clearly define the public suffix + 1 scope for browsers while still allowing for cases like that OAuth one might be useful.

**Comment by balfanz** [comment]
"Earlier in the document" means normative sections, no? I agree that the scoping rules might be different for OAuth clients, etc., so I hesitate to put any normative language in the spec for this. Hence its current location in the Privacy Considerations.

What do you think?

**Comment by equalsJeffH** [comment]
Note that we discussed scoping rules on the mailing list a while back, here's Dirk's reply wherein he notes adding the "Scoping of Token Binding Keys" section to "privacy consideratsions" and also replies to questions regarding hosts/servers denoted by IP address:  https://mailarchive.ietf.org/arch/msg/unbearable/Ej0QwBvg2vTbFNqA0eadU2lHGJ4

**Comment by b---c** [comment]
I hadn't thought of it that way, Dirk, to be honest. Maybe it should stay in privacy considerations with just a mention and forward reference to it earlier in the document. 

When I first read (a version of) the draft, I was uncertain about the scoping until late in the doc. And I've had some conversations with people about TB where they jump to concerns about a super cookie like tracking mechanism and I have to explain why it's not the case. So, just from my experience, it seemed like saying something earlier or more prominently in the document would be a good thing.

I guess, from my POV, it'd be nice if it could say clearly somewhere that ETLD must be the scoping for web browser clients and that other higher level protocols on top of HTTPS can do their own scoping but should go with ETLD unless there's a compelling reason to do otherwise. 

I think Jeff's text in PR#49 is along the right track. The SHOULD for OAUTH is a bit strong - at least until we know better what we are doing there. I think the bit about hosts/servers denoted by IP address is still needed. Can we just say web browsers doing HTTPS must scope at ETLD? The talk of cookies is useful to understand why but maybe the kinds of clients that have to do it can be more explicit.
