### ISSUE TITLE
HTTPSTB: distinct header for the referred Token Binding

### ISSUE THREAD

**Issue by b---c** [TokenBinding/Internet-Drafts#35]
As mentioned [at IETF 95](https://datatracker.ietf.org/doc/minutes-95-tokbind/) I propose that the referred Token Binding be sent via a separate header (say Sec-Referred-Token-Binding) rather than as part of the Sec-Token-Binding header. 

At the HTTP layer separate headers will make it much more clear what is going on. Just looking for the presence or absence of the Sec-Referred-Token-Binding header will indicate if a referred TB was sent, which is very easy. Rather than having to decode the Sec-Token-Binding header value and process the binary content, which is possible but much more involved. 

Having a separate header for the referred TB allows the client/user agent to always send the provided TB via Sec-Token-Binding and not have to build a new TB message on the redirect request and then go back to the provided TB on subsequent requests. Also not having the value of Sec-Token-Binding change (other then a new TLS session with new EKM) should make it nicely efficient with HTTP/2 header compression. 

I also believe it will be easier to covey the concepts in the text of the spec. Talking about when the Sec-Referred-Token-Binding is sent or not sent rather than talking about when the referred TB is included as part of the TB message that is sent with Sec-Token-Binding seems much more straightforward. 

Anecdotally, there's been some discussion about using TB in OpenID Connect and and in talking about it people often say "the referred token binding header", which isn't accurate relative to HTTPSTB-03 but belies the fact that federation folks already think about it as separate header. And I think that's a natural way think about it so it's not terribly surprising. I won't name any names but one of the chairs of the WG is among those who said "the referred token binding header."

I realize this is not an insignificant change but I strongly believe it'd be a simplification and improvement for HTTPS TB. There's not yet (that I'm aware of anyway) any profiling of TB for federation like protocols such OpenID Connect, OAuth or SAML so this would be an opportune time to change how the referred Token Binding is conveyed.

**Comment by Andrei-Popov** [comment]
The current format, where all Token Bindings are contained in one Token Binding message, provides useful encapsulation. The HTTP layer does not need to know the details of the Token Binding protocol, which can be implemented in a separate library. If tomorrow we define a new Token Binding type, an existing HTTP implementation can carry it in the Sec-Token-Binding header without modification. Only the Token Binding library would need to be updated.

 At the HTTP layer separate headers will make it much more clear what is going on. Just looking for the presence or absence of the Sec-Referred-Token-Binding header will indicate if a referred TB was sent, which is very easy.
This can be solved by including a TB parser in the protocol analyzer. Which would also provide further useful insights into TB key parameters, etc.

 Having a separate header for the referred TB allows the client/user agent to always send the provided TB via Sec-Token-Binding and not have to build a new TB message on the redirect request and then go back to the provided TB on subsequent requests.
I don’t think there’s an optimization an HTTP stack can do WRT building TB messages that a Token Binding library can’t, and the Token Binding library is where such optimizations belong.

For the above reasons, I would prefer to keep all Token Bindings in one Token Binding message.

**Comment by b---c** [comment]
Discussion happening on the WG list too: http://www.ietf.org/mail-archive/web/unbearable/current/msg00515.html

**Comment by b---c** [comment]
Closing this one as I was unable to gather support for the change or sway the opinion of an editor. http://www.ietf.org/mail-archive/web/unbearable/current/msg00529.html and previous have some of the discussion.

**Comment by b---c** [comment]
Closing this one as I was unable to gather support for the change or sway the opinion of an editor. http://www.ietf.org/mail-archive/web/unbearable/current/msg00529.html and previous have some of the discussion.
