### ISSUE TITLE
HTTPSTB: Add Acknowledgements 

### ISSUE THREAD

**Issue by b---c** [TokenBinding/Internet-Drafts#36]
It's pretty standard practice and generally just common courtesy to have an Acknowledgements section/appendix, however, as of -03 there's not one in draft-ietf-tokbind-https.  I know it's kind of petty but, if my name is on there, it's something I can show my mother to try and prove that I'm not a total failure in life. More seriously, being listed in acknowledgements can be helpful and show proof of work for those who have to justify the time they spend contributing to the spec to their employer or whoever pays for their time. 

Here's some text adapted from a different draft that could be used. Or the more terse text from TBPROTO and TBNEG works, if the authors prefer.   

>   This specification was developed within the Token Binding Working Group,
>   which includes dozens of active and dedicated participants.  It was
>   produced under the chairmanship of John Bradley and Leif Johansson
>   with Kathleen Moriarty and Stephen Farrell serving as Security Area
>   Directors.  The following individuals contributed ideas, feedback,
>   and wording to this specification:
> 
> [[ names here ]]

I don't know the full list of names but the sooner the list gets started the easier it will be to track. Maybe look though minutes and the list. Or ask.

**Comment by b---c** [comment]
_maybe_ Nick Harper, Vinod Anupam, Martin Thomson, Scott Cantor, others

**Comment by Andrei-Popov** [comment]
Done in HTTPSTB-04.
