### ISSUE TITLE
TBPROTO: provide some examples

### ISSUE THREAD

**Issue by b---c** [TokenBinding/Internet-Drafts#39]
I think there'd be real value in providing some examples in TBPROTO (and also maybe HTTPSTB) that could help serve to validate reader's interpretation of the text.

As an implementer of JWS & JWE, for instance, I found the examples in the documents to be exceptionally valuable in aiding my understanding and helping to vet the implementation. I think some example TokenBindingMessages in the TB doc(s) could be similarly valuable.

I'd been thinking about suggesting it for a while. Then some of the questions and stated interpretations in [the thread](http://www.ietf.org/mail-archive/web/unbearable/current/threads.html#00514) leading up to [my saying something similar on the WG list](http://www.ietf.org/mail-archive/web/unbearable/current/msg00546.html) reminded me about it and reinforced that even clearly written text and "TLS Presentation Language" can be interpreted different ways by different people. Examples can be very helpful with that.

**Comment by Andrei-Popov** [comment]
For me personally, looking at large BLOBs doesn't help much. The spec relies on the reader understanding the "TLS presentation language". However, I don't feel strongly about this; if there is WG support for adding sample message BLOBs to the spec, I can do it once our implementation is up to date with the spec.

**Comment by b---c** [comment]
Agree that just looking at BLOBs doesn't help much or at all. The value, I think, is providing an early sanity check for implementations. Or parts of implementations anyway. Several of the key parameter type's signatures aren't deterministic so one can't just reproduce examples for those. But if one can verify the examples and produce results that can also be verified, it's a pretty good sign things are in good shape. The EKM value needs to be provided with the example too for such implementation checks to be possible. Such examples can help drive out interoperability problems earlier on before implementations actually interoperate.

**Comment by b---c** [comment]
Here are a couple of TokenBindingMessages produced by Chrome Canary and validated with code I wrote (so semi confident that they are correct). 

**This one has a single ecdsap256 provided token binding :**
TokenBindingMessage: `[0, 135, 0, 2, 64, 32, 73, 230, 99, 203, 36, 207, 24, 103, 79, 159, 0, 238, 132, 135, 175, 167, 87, 165, 15, 130, 169, 136, 57, 4, 210, 72, 101, 28, 230, 161, 187, 73, 244, 2, 99, 163, 248, 100, 60, 63, 220, 98, 227, 57, 232, 238, 135, 8, 197, 7, 13, 248, 103, 46, 146, 66, 56, 216, 158, 130, 85, 52, 113, 0, 64, 141, 140, 40, 147, 111, 16, 161, 207, 132, 223, 89, 97, 189, 179, 243, 207, 120, 167, 175, 72, 0, 166, 193, 207, 240, 24, 41, 85, 2, 80, 9, 7, 254, 133, 111, 68, 30, 146, 53, 69, 198, 3, 170, 43, 168, 91, 65, 197, 79, 215, 207, 1, 77, 136, 114, 41, 212, 125, 24, 249, 174, 18, 88, 190, 0, 0]`
Base64url encoded TokenBindingMessage: `AIcAAkAgSeZjyyTPGGdPnwDuhIevp1elD4KpiDkE0khlHOahu0n0AmOj-GQ8P9xi4zno7ocIxQcN-GcukkI42J6CVTRxAECNjCiTbxChz4TfWWG9s_PPeKevSACmwc_wGClVAlAJB_6Fb0QekjVFxgOqK6hbQcVP188BTYhyKdR9GPmuEli-AAA`
EKM: `[251, 106, 16, 126, 68, 133, 18, 244, 226, 13, 10, 209, 1, 7, 188, 125, 102, 140, 227, 208, 169, 195, 152, 18, 160, 165, 86, 101, 35, 134, 224, 166]`
Base64url encoded EKM: `-2oQfkSFEvTiDQrRAQe8fWaM49Cpw5gSoKVWZSOG4KY `

**This one has a ecdsap256 provided and referred token binding:**
TokenBindingMessage: `[1, 14, 0, 2, 64, 185, 78, 236, 69, 100, 221, 93, 160, 223, 236, 230, 129, 26, 106, 218, 162, 159, 111, 14, 133, 214, 182, 125, 237, 141, 121, 178, 38, 38, 142, 236, 183, 83, 144, 138, 53, 204, 23, 158, 177, 216, 168, 207, 59, 61, 200, 165, 122, 2, 123, 58, 140, 93, 236, 170, 98, 68, 100, 72, 167, 152, 194, 1, 122, 0, 64, 110, 161, 137, 8, 254, 228, 94, 178, 154, 152, 44, 186, 82, 41, 125, 231, 190, 78, 224, 136, 238, 71, 80, 239, 78, 176, 115, 22, 65, 216, 91, 249, 120, 53, 87, 89, 75, 223, 246, 165, 27, 182, 0, 124, 174, 240, 2, 114, 139, 167, 111, 128, 98, 240, 244, 115, 173, 37, 249, 233, 120, 76, 106, 6, 0, 0, 1, 2, 64, 82, 225, 38, 192, 194, 224, 125, 173, 193, 178, 213, 119, 32, 176, 126, 112, 196, 212, 85, 239, 108, 117, 31, 106, 227, 180, 126, 162, 51, 21, 128, 212, 136, 132, 129, 2, 155, 89, 143, 244, 233, 52, 32, 166, 161, 121, 103, 182, 212, 189, 191, 235, 68, 71, 199, 124, 183, 232, 223, 0, 69, 218, 208, 179, 0, 64, 134, 244, 179, 39, 190, 58, 163, 55, 245, 95, 100, 217, 122, 170, 130, 19, 72, 168, 197, 123, 199, 118, 13, 130, 103, 227, 22, 230, 177, 16, 87, 78, 75, 39, 88, 28, 185, 226, 63, 40, 188, 105, 22, 116, 151, 136, 156, 33, 16, 97, 214, 154, 79, 214, 148, 190, 212, 242, 42, 146, 99, 212, 130, 87, 0, 0]`
Base64url encoded TokenBindingMessage: `AQ4AAkC5TuxFZN1doN_s5oEaatqin28Ohda2fe2NebImJo7st1OQijXMF56x2KjPOz3IpXoCezqMXeyqYkRkSKeYwgF6AEBuoYkI_uRespqYLLpSKX3nvk7giO5HUO9OsHMWQdhb-Xg1V1lL3_alG7YAfK7wAnKLp2-AYvD0c60l-el4TGoGAAABAkBS4SbAwuB9rcGy1XcgsH5wxNRV72x1H2rjtH6iMxWA1IiEgQKbWY_06TQgpqF5Z7bUvb_rREfHfLfo3wBF2tCzAECG9LMnvjqjN_VfZNl6qoITSKjFe8d2DYJn4xbmsRBXTksnWBy54j8ovGkWdJeInCEQYdaaT9aUvtTyKpJj1IJXAAA`
EKM: `[234, 61, 72, 151, 56, 73, 156, 5, 160, 173, 240, 104, 217, 237, 184, 217, 86, 77, 183, 171, 194, 35, 55, 74, 241, 159, 252, 213, 174, 223, 92, 184]`
Base64url encoded EKM: `6j1IlzhJnAWgrfBo2e242VZNt6vCIzdK8Z_81a7fXLg`

**Comment by b---c** [comment]
Here are a couple of -10 TokenBindingMessages produced by Chrome Canary and independently validated with code I wrote (so semi kinda pretty confident that they are correct).

**This one has a single ecdsap256 provided token binding :**
TokenBindingMessage: `[0, 137, 0, 2, 0, 65, 64, 185, 78, 236, 69, 100, 221, 93, 160, 223, 236, 230, 129, 26, 106, 218, 162, 159, 111, 14, 133, 214, 182, 125, 237, 141, 121, 178, 38, 38, 142, 236, 183, 83, 144, 138, 53, 204, 23, 158, 177, 216, 168, 207, 59, 61, 200, 165, 122, 2, 123, 58, 140, 93, 236, 170, 98, 68, 100, 72, 167, 152, 194, 1, 122, 0, 64, 34, 225, 100, 135, 146, 81, 53, 175, 220, 68, 202, 111, 218, 143, 15, 37, 179, 198, 100, 37, 192, 80, 197, 146, 103, 134, 74, 138, 97, 10, 209, 4, 117, 243, 167, 176, 170, 45, 100, 211, 160, 67, 113, 115, 220, 50, 48, 29, 150, 254, 26, 167, 100, 142, 129, 226, 84, 223, 225, 0, 78, 93, 27, 232, 0, 0]`
Base64url encoded TokenBindingMessage: `AIkAAgBBQLlO7EVk3V2g3-zmgRpq2qKfbw6F1rZ97Y15siYmjuy3U5CKNcwXnrHYqM87PcilegJ7Ooxd7KpiRGRIp5jCAXoAQCLhZIeSUTWv3ETKb9qPDyWzxmQlwFDFkmeGSophCtEEdfOnsKotZNOgQ3Fz3DIwHZb-GqdkjoHiVN_hAE5dG-gAAA`
EKM: `[231, 60, 251, 165, 175, 127, 172, 129, 132, 239, 214, 106, 245, 241, 20, 158, 95, 146, 108, 176, 165, 170, 77, 74, 245, 182, 172, 246, 21, 153, 251, 252]`
Base64url encoded EKM: `5zz7pa9_rIGE79Zq9fEUnl-SbLClqk1K9bas9hWZ-_w`

**This one has a ecdsap256 provided and referred token binding:**
TokenBindingMessage:`[1, 18, 0, 2, 0, 65, 64, 185, 78, 236, 69, 100, 221, 93, 160, 223, 236, 230, 129, 26, 106, 218, 162, 159, 111, 14, 133, 214, 182, 125, 237, 141, 121, 178, 38, 38, 142, 236, 183, 83, 144, 138, 53, 204, 23, 158, 177, 216, 168, 207, 59, 61, 200, 165, 122, 2, 123, 58, 140, 93, 236, 170, 98, 68, 100, 72, 167, 152, 194, 1, 122, 0, 64, 160, 159, 196, 249, 249, 68, 33, 244, 30, 132, 126, 199, 248, 144, 56, 160, 184, 232, 190, 12, 110, 208, 171, 225, 97, 174, 93, 53, 124, 151, 117, 100, 133, 81, 6, 151, 137, 44, 112, 57, 86, 89, 71, 3, 65, 95, 204, 106, 45, 135, 121, 40, 158, 132, 207, 33, 7, 43, 184, 99, 205, 28, 237, 157, 0, 0, 1, 2, 0, 65, 64, 82, 225, 38, 192, 194, 224, 125, 173, 193, 178, 213, 119, 32, 176, 126, 112, 196, 212, 85, 239, 108, 117, 31, 106, 227, 180, 126, 162, 51, 21, 128, 212, 136, 132, 129, 2, 155, 89, 143, 244, 233, 52, 32, 166, 161, 121, 103, 182, 212, 189, 191, 235, 68, 71, 199, 124, 183, 232, 223, 0, 69, 218, 208, 179, 0, 64, 250, 169, 130, 88, 107, 124, 60, 48, 112, 44, 113, 48, 172, 76, 44, 96, 23, 173, 102, 63, 195, 179, 38, 68, 232, 237, 202, 120, 101, 163, 22, 59, 1, 161, 119, 37, 25, 68, 49, 240, 38, 45, 144, 231, 200, 45, 61, 143, 65, 92, 171, 250, 141, 223, 48, 218, 246, 9, 255, 197, 72, 248, 215, 66, 0, 0]`
Base64url encoded TokenBindingMessage: `ARIAAgBBQLlO7EVk3V2g3-zmgRpq2qKfbw6F1rZ97Y15siYmjuy3U5CKNcwXnrHYqM87PcilegJ7Ooxd7KpiRGRIp5jCAXoAQKCfxPn5RCH0HoR-x_iQOKC46L4MbtCr4WGuXTV8l3VkhVEGl4kscDlWWUcDQV_Mai2HeSiehM8hByu4Y80c7Z0AAAECAEFAUuEmwMLgfa3BstV3ILB-cMTUVe9sdR9q47R-ojMVgNSIhIECm1mP9Ok0IKaheWe21L2_60RHx3y36N8ARdrQswBA-qmCWGt8PDBwLHEwrEwsYBetZj_DsyZE6O3KeGWjFjsBoXclGUQx8CYtkOfILT2PQVyr-o3fMNr2Cf_FSPjXQgAA`
EKM: `[69, 218, 67, 133, 84, 79, 45, 24, 148, 55, 227, 128, 173, 2, 222, 45, 1, 1, 135, 85, 34, 212, 177, 151, 174, 124, 164, 87, 20, 204, 65, 36]`
Base64url encoded EKM: `RdpDhVRPLRiUN-OArQLeLQEBh1Ui1LGXrnykVxTMQSQ`

**Comment by b---c** [comment]
I find it extremely helpful to have example messages to work from but if I'm in the minority, we can let this issue go. 

I'd like to see some RSA examples too (I'm confident in my ecdsap256 consumption/verification implementation b/c I could test it against what Chrome produced). But again, maybe it's only me.

**Comment by b---c** [comment]
I seem to be in a minority on wanting example messages and thanks to @nharper and Chrome have had 'real' example messages to work with. 

I'm closing this issue without prejudice.

**Comment by equalsJeffH** [comment]
alrightie then :)
