### ISSUE TITLE
Consider extensions

### ISSUE THREAD

**Issue by martinthomson** [TokenBinding/Internet-Drafts#4]
In addition to _using_ extensions as I suggested in #3, I think that the extension field in the TokenBinding structure is more likely to be a liability than an asset.

This is something that could conceivably be modified by a future extension to TLS if extension if a need is identified.

**Comment by TokenBinding** [comment]
Token Binding extensions are part of Token Binding messages, not TLS messages. They can be used when Token Binding is running on top of a security protocol other than TLS.

**Comment by martinthomson** [comment]
The function of this extension/message is clearly proscribed: proof of possession.  We don't understand any need for extension.  That makes an extensibility point hard to understand and get right.

Extension might, in this case, be supported better by making a new TLS extension, or by minting a replacement header field if new information needs to be added.

**Comment by Andrei-Popov** [comment]
> The function of this extension/message is clearly proscribed: proof of possession. 
> We don't understand any need for extension. 

One example use of an extension would be to carry an attestation statement, i.e. proof of hardware binding of the key.

> Extension might, in this case, be supported better by making a new TLS extension, or by minting a replacement header field if new information needs to be added.

In our example, attestation pertains to a particular token binding key, and the extension structure in the TokenBinding message helps express this. Cross-referencing TLS extensions with HTTP headers, or cross-referencing different HTTP headers does not seem like a good idea.

**Comment by leifj** [comment]
Folks - remember to mirror the discussion on the IETF-list. Discussions on github are not obviously covered by NOTE WELL.
