### ISSUE TITLE
HTTPSTB: different text re Triple Handshake Vulnerability than TBPROTO & TBNEGO

### ISSUE THREAD

**Issue by b---c** [TokenBinding/Internet-Drafts#40]
The Security Considerations about the Triple Handshake Vulnerability at https://tools.ietf.org/html/draft-ietf-tokbind-https-03#section-4.2 is different (looks maybe older) than https://tools.ietf.org/html/draft-ietf-tokbind-protocol-06#section-8.5 and https://tools.ietf.org/html/draft-ietf-tokbind-negotiation-02#section-6.2

I'm guessing it's just an oversight?

**Comment by Andrei-Popov** [comment]
Addressed in HTTPSTB-04.
