### ISSUE TITLE
TBNEGO: right place for registration of key parameters?

### ISSUE THREAD

**Issue by b---c** [TokenBinding/Internet-Drafts#41]
In [TBNEGO section 5](https://tools.ietf.org/html/draft-ietf-tokbind-negotiation-02#section-5) the initial set of registrations for the "Token Binding Key Parameters" registry list "this document" as "A reference to a specification that defines the Token Binding key parameters" for rsa2048_pkcs1.5, rsa2048_pss and ecdsap256. And they are kind of defined in [TBNEGO section 2](https://tools.ietf.org/html/draft-ietf-tokbind-negotiation-02#section-2) with the TLS Presentation Language but it seems they are really more fully defined in [TBPROTO section 3](https://tools.ietf.org/html/draft-ietf-tokbind-protocol-06#section-3).

Sorry, I realize it's pedantic but it did strike me as odd/awkward when reading it. And someday the registry will link to the documents where the parameter(s) are specified, which could be confusing, if it's to TBNEGO.    

Should the "Specification:" bit of the registration for the key parameters also or alternatively point to TBPROTO? Or should the registrations be moved to TBPROTO?

**Comment by Andrei-Popov** [comment]
Fixed in TBPROTO-07 and TBNEGO-03.
