### ISSUE TITLE
HTTPSTB: use "same-site" rather than "first-party" terminology

### ISSUE THREAD

**Issue by equalsJeffH** [TokenBinding/Internet-Drafts#44]
In the HTTP WG's efforts to update the  "cookies" spec RFC6265, we've settled on the terms "same-site" (rather than "first-party") and "cross-site" (rather than "third-party"). 

I do not doubt HTTPSTB will receive feedback during last calls on the  "first-party" and "federation" terms, and so think we should make such a terminology change now.   We can do it by drawing equivalence between "same-site" & "first-party", and  "federation" & "cross-site".

see also: https://tools.ietf.org/html/draft-ietf-httpbis-cookie-same-site, and #43

**Comment by ve7jtb** [comment]
That make sense to do now.

**Comment by balfanz** [comment]
Mmh - I'm not so sure. "Same-site" and "cross-site" makes sense in a browser setting, where Javascript code is delivered from a first site, and then that code accesses a second site - which may or may not be the same site as the first.

HTTP is more general than browsers and Javascript, though. Imagine an Acme client app that I downloaded from an app store, which accesses Acme services in the cloud. Something like that is covered by the I-D, but it's "first party", not "same site", right?

**Comment by equalsJeffH** [comment]
AFAICT, in a general HTTP client context, the terms "first party" and "same site" are essentially equivalent.  If that is agreed and we clearly draw equivalence between the terms, then we're probably ok regardless whether we primarily use one term or the other, and I'm ok with either I suppose, but again, in the upcoming mods to cookies spec it looks like we'll be using "same site".

In terms of "federation" & "cross-site" & "third-party" I agree that "cross-site" is inapt. good catch, thanks.  Do we wish to draw equivalence between "federation" and "third-party"?
