### ISSUE TITLE
TBPROTO: Treating Token Binding ID as an opaque byte sequence

### ISSUE THREAD

**Issue by equalsJeffH** [TokenBinding/Internet-Drafts#48]
Mike Jones notes in: https://www.ietf.org/mail-archive/web/unbearable/current/msg00582.html
In a private conversation with Andrei, we talked about adding a note to the spec recommending that Token Binding APIs treat the Token Binding ID as an opaque byte sequence, rather than as the structure defined in the protocol (type byte, followed by public key representation).  Doing so would allow the Token Binding ID contents to change in future protocol versions without breaking applications.

This is a reminder to add this note to the spec.

**Comment by Andrei-Popov** [comment]
Fixed in TBPROTO-07.
