### ISSUE TITLE
Signature algorithm negotiation in HTTP

### ISSUE THREAD

**Issue by martinthomson** [TokenBinding/Internet-Drafts#5]
The current draft uses ALPN, which in #3 I note isn't necessarily a good idea.  However, using the signature algorithm extension in TLS is not going to be visible to the HTTP implementation.  There needs to be a better way of determining what sorts of bindings will be acceptable.

One very simple way is to make the signature algorithm fixed in this version.  I realize that flies against all the old advice on algorithm agility, but we can always mint a new header field if the algorithms we choose turn out to be unfashionable in 5 years time.  Either that or the header field could be parameterized (my preference) so that multiple values can be provided with the label identifying the signature format.  If so, beware the linkability that could generate and note it in the privacy considerations.

**Comment by Andrei-Popov** [comment]
> One very simple way is to make the signature algorithm fixed in this version. 
> I realize that flies against all the old advice on algorithm agility, but we can always mint a new header field if the algorithms we choose turn out to be unfashionable in 5 years time.

I think we will have trouble agreeing on just one algorithm, especially considering the fact that hardware binding is desirable.

> Either that or the header field could be parameterized (my preference) so that multiple values can be provided with the label identifying the signature format.

This is already supported in the current -00 draft and its implementations. Providing multiple signatures is expensive though, especially if the signatures are performed by secure hardware. So I don't expect a lot of implementations sending multiple signatures.

What if we used a different TLS extension to negotiate Token Binding key parameters?

**Comment by Andrei-Popov** [comment]
Agreement has been reached in Dallas that we will define a new TLS extension to negotiate Token Binding key parameters, instead of using ALPN. I'm planning to publish a new I-D for the TLS extension, and update  draft-ietf-tokbind-protocol in the next 2-3 weeks.

**Comment by Andrei-Popov** [comment]
Added TBNEGO I-D specifying a TLS extension for TB negotiation.
