### ISSUE TITLE
TBPROTO: add "TLS" to spec title

### ISSUE THREAD

**Issue by equalsJeffH** [TokenBinding/Internet-Drafts#50]
TBPROTO uses the term "TLS Token Binding" in 28 places. 

Perhaps we ought to alter the spec title to be..

> The TLS Token Binding Protocol Version 1.0

..or..

> TLS Token Binding Protocol Version 1.0

Waddyathink?

**Comment by Andrei-Popov** [comment]
If the purpose is to harmonize terminology, I would prefer getting rid of "TLS" and leaving "Token Binding" in those 28 places.

**Comment by equalsJeffH** [comment]
Well, TBPROTO is presently written specifically in terms of TLS, and we decided to hold off on generalizing the spec for other secure transport layers..

https://www.ietf.org/mail-archive/web/unbearable/current/msg00347.html

..so it's arguably a TLS-specific spec.   but, I don't feel strongly about it.  harmonizing the terminology would be good, in either fashion.

**Comment by Andrei-Popov** [comment]
Harmonized terminology in TBPROTO-08.
