### ISSUE TITLE
HTTPSTB: add "TLS" to spec title?

### ISSUE THREAD

**Issue by equalsJeffH** [TokenBinding/Internet-Drafts#51]
See also #50 
Perhaps we should alter the HTTPSTB spec title to be..

> TLS Token Binding over HTTP

..?

**Comment by Andrei-Popov** [comment]
Unless there's an important reason to do so, I prefer the current, shorter, names.

**Comment by Andrei-Popov** [comment]
Harmonized terminology in TBPROTO-08.
