### ISSUE TITLE
HTTPSTB: Clarify that base64url encoding means no padding.

### ISSUE THREAD

**Issue by balfanz** [TokenBinding/Internet-Drafts#56]
We should clarify that the Sec-Token-Binding header shouldn't have any padding appended as part of the base64 encoding.

**Comment by equalsJeffH** [comment]
how about the language proposed by @b---c here:  https://github.com/TokenBinding/Internet-Drafts/issues/27#issuecomment-217980935  ?

**Comment by b---c** [comment]
PR #57 has language very similar to what was suggested in the comment on issue #27

**Comment by Andrei-Popov** [comment]
Fixed by merging PR #57.
