### ISSUE TITLE
HTTPSTB: MUST issue an unbound token -> MUST NOT issue a bound token?

### ISSUE THREAD

**Issue by b---c** [TokenBinding/Internet-Drafts#59]
https://tools.ietf.org/html/draft-ietf-tokbind-https-05#section-4.4 

```
   If a token provider
   does not support the key parameters specified in the
   referred_token_binding TokenBinding in the TokenBindingMessage, it
   MUST issue an unbound token.
```

which I think could potentially be misconstrued as not giving the token provider the option to not issue a token at all (for whatever reason). It's kind of a nit but a fairly literal reading. 

I think perhaps the following text captures the intent with less room for misunderstanding. 

```
   If a token provider
   does not support the key parameters specified in the
   referred_token_binding TokenBinding in the TokenBindingMessage, it
   MUST NOT issue a bound token.
```

**Comment by Andrei-Popov** [comment]
Fixing in HTTPSTB-06.
