### ISSUE TITLE
Are there two lengths for RSA?

### ISSUE THREAD

**Issue by martinthomson** [TokenBinding/Internet-Drafts#60]
> RSAPublicKey.modulus and
>    RSAPublicKey.publicexponent contain the length-prefixed modulus and
>    exponent of the RSA public key represented in big-endian format.

I think that this is potentially confusing; I would remove "length-prefixed" from this statement given that a length prefix is implied by the TLS encoding.  Saying that the modulus is length-prefixed here might be interpreted as saying that there is _another_ length within the structure.  That's probably not the case.

**Comment by Andrei-Popov** [comment]
Sure, fixing in -09.
