### ISSUE TITLE
Token bindings of unknown types make later token bindings unusable

### ISSUE THREAD

**Issue by martinthomson** [TokenBinding/Internet-Drafts#61]
`TokenBindingMessage` contains a single list of `TokenBinding` objects.  That means that there is a single 2 octet length for the entire message.  (This is redundant in most encodings, but that's the price you pay for reusing the TLS grammar for defining these things.)

A `TokenBinding` object that contains a `tokenbindingid` that isn't understood by its recipient is of indeterminite length.  That recipient can decode `tokenbinding_type` and `tokenbindingid.key_parameters`, but won't be able to decode `TokenBindingID.<select>` because it can't know what the length is.

`rsa2048_pss` and `rsa2048_pkcs1.5` have a two octet length; ecdsap256 has a one octet length; any other type is unknown.  This makes it impossible to locate the start of the signature, which is needed to find the end of the struct.

As a result, any `TokenBinding` objects that follow an unsupported object can't be located, once an unsupported token is encountered, all remaining tokens are unreadable.  Presumably this is OK because the supported types are negotiated.

A simple fix would be to include a length in the structure.  This would enable other modalities of use where supported types are not strictly negotiated ahead of time.

Note that the definition of `TokenBindingID` needs to include a name for the select, and a trailing semi-colon (#66).

**Comment by b---c** [comment]
The referred token binding is a case where the supported types are not negotiated (as [mentioned on the list](https://www.ietf.org/mail-archive/web/unbearable/current/msg00666.html)) so it is possible for a TokenBindingMessage with an unknown type to be encountered.

**Comment by Andrei-Popov** [comment]
Fixing this in -09.
