### ISSUE TITLE
TBPROTO: Terminating connections

### ISSUE THREAD

**Issue by martinthomson** [TokenBinding/Internet-Drafts#64]
-protocol [aka TBPROTO] says:

> The server MUST terminate the connection if the use of the Token
>    Binding protocol was not negotiated, but the client sends the Token
>    Binding message.

and

> In the case of a mismatch, the
>    server MUST terminate the connection.  [referring to signature validation]

HTTP is generally tolerant - at least at the connection level - of errors in individual requests.  Since -protocol is protocol agnostic, this has to be generic advice, but that advice should instead be to recommend that the using protocol fail whatever transaction the token binding is attached to.  For HTTP, that's a request, for which a 4xx-series status code is more appropriate than dumping the connection.  

Note that HTTP has provisions for cases where a peer misbehaves; repeated abuse in the form of bad token bindings can be dealt with on that basis.

For the first case, it's fine for the server to require that token bindings be correct if provided.  But that's very different from requiring the server to reject token bindings blindly.  Defining correctness in terms of what token binding types were negotiated for the connection can achieve the same effect.

**Comment by Andrei-Popov** [comment]
The reason we're terminating the connection is that we're talking to a broken, malicious or MITM-ed peer.
Arguably, these are protocol-level failures, not just individual request failures such as a GET for a non-existent page.

**Comment by equalsJeffH** [comment]
I have all along wondered about the same thing @martinthomson describes above.  If we tokbind WG agree that the presently-specified behavior is OK, then we ought to include in the spec the rationale that @Andrei-Popov relates.

**Comment by equalsJeffH** [comment]
I have all along wondered about the same thing @martinthomson describes above.  If we tokbind WG agree that the presently-specified behavior is OK, then we ought to include in the spec the rationale that @Andrei-Popov relates.

**Comment by Andrei-Popov** [comment]
TBPROTO-11 replaces "connection termination" with a rejection of the binding and its associated bound tokens. The effect of this is application-specific, e.g. failing requests, the need for the client to re-authenticate and present new token(s), or connection termination.
