### ISSUE TITLE
TBPROTO: TLS extension is not generic because the requirement is not generic

### ISSUE THREAD

**Issue by martinthomson** [TokenBinding/Internet-Drafts#65]
The theory behind having a separate document and mechanism for negotiating support for token binding is that it remains portable.  This is not the case, since the example in the -protocol doc contradicts many of the reasons for having parameter negotiation in the TLS layer.

Here's the offending text:

> In the case of a server-
>    initiated challenge-response protocol employing Token Binding and
>    TLS, the client can, for example, incorporate the Token Binding ID
>    within the signed object it returns, thus binding the object.

In this case, a server could, as part of its challenge, indicate which sorts of tokens it is willing to accept.

The real reason that negotiation happens at the TLS layer is that this is needed for performance in HTTPS.  Clients want to know what options are available to it when it generates the first request.

Rather than structure the documents so that https -> protocol -> negotiation, the protocol doc could generically describe negotiation and the https document could describe a dependency on TLS negotiation.

**Comment by Andrei-Popov** [comment]
It is true that conceivably there are multiple negotiation options. TBNEGO describes one of them (via TLS extension). I think it's good to keep it in a separate doc, but then again we've argued over this in the past on the mailing list and in meetings.

**Comment by equalsJeffH** [comment]
@martinthomson  is not suggesting to fundamentally alter the three separate specs.  Rather, he is suggesting that TBPROTO generically wave its hands regarding TB negotiation (it could happen in a TLS extension, it could happen in the app layer, etc), and have HTTPSTB make the normative reference to TBNEGO for negotiation -- i.e., in HTTPS's specific context.

I think this idea has merit, but can go either way.  If there is a TB v2 envisioned (if not why have the spec explicitly say v1 as it presently does?), it could be done then.

**Comment by equalsJeffH** [comment]
shall we close this issue?

**Comment by Andrei-Popov** [comment]
Both #65 and #69 seem intractable to me.
