### ISSUE TITLE
TokenBindingID select definition

### ISSUE THREAD

**Issue by martinthomson** [TokenBinding/Internet-Drafts#66]
The definition of `TokenBindingID` needs to include a name for the select, and a trailing semi-colon.

**Comment by Andrei-Popov** [comment]
Quoth the TLS 1.2 RFC: 
"The body of the variant structure may be given a label for reference."
"} variant_body;       /\* optional label on variant */"

So the label is optional, but you're right about the semi-colon. Will fix in -09.
