### ISSUE TITLE
Clients that limit cookies

### ISSUE THREAD

**Issue by martinthomson** [TokenBinding/Internet-Drafts#68]
A number of clients can be configured to limit the scope over which a cookie is used (in time, origins, or otherwise).  This specification provides persistent information that crosses the usual origin boundaries.

Even when the normal origin boundaries are observed, the current trend is to be a lot more precise about what visibility is given to state.  See for example w3c/mediacapture-main#381.  This spec needs to talk about how this state is managed, what user visibility it needs, and what clients that might not have default behaviour regarding cookies might do to ensure that this has similar properties to the cookies that it attempts to mimic.

**Comment by Andrei-Popov** [comment]
The clients that limit the scope of cookies should probably also limit the scope of TB keys to match. Would this be the right solution?

**Comment by ve7jtb** [comment]
Personally I would be OK with that.   I think that always limiting TB to same origin when the client is allowing a more liberal cookie policy in ways that will frustrate users and developers.

John B.

**Comment by Andrei-Popov** [comment]
Adding the scope language in -09.
