### ISSUE TITLE
HTTPSTB: Origin binding

### ISSUE THREAD

**Issue by martinthomson** [TokenBinding/Internet-Drafts#69]
This feature would be equivalently functional if it were restricted to origins rather than eTLD+1.  It might be more difficult to use.  That is, if https://x.example.com receives a token binding and creates a cookie for *.example.com, then https://y.example.com would have to talk to to https://x.example.com to validate that the token is valid.

Maybe this is a big pain, but so is dealing with new state establishment mechanisms that span origins.  We've not done one since cookies because we have realized that cookies were a mistake.  Maybe we shouldn't be repeating that mistake.

**Comment by Andrei-Popov** [comment]
Based on the mailing list discussion, many feel that such a change in HTTPSTB would be a deployment blocker, at least for some scenarios.

**Comment by equalsJeffH** [comment]
closing this issue given @Andrei-Popov 's comment above, two thumbs-up, and no dissension.
