### ISSUE TITLE
Clarify the use of SHA256 for PKCS and PSS padding. Define salt length for PSS.

### ISSUE THREAD

**Issue by Andrei-Popov** [TokenBinding/Internet-Drafts#70]

**Comment by pranavkukreja** [comment]
Notes: Crypto team recommendation from Microsoft is hash length (n bytes) of the hash algorithm used in the padding. In this case, n =  32 (SHA256 length in bytes) for the salt length (for PSS padding only). Salt is recoverable on the server side, but implementations need to know how many bytes to recover, and should therefore use the same salt length on both client and server.

**Comment by Andrei-Popov** [comment]
Yes, Google folks seem to concur. I'm clarifying this in the TBPROTO-09 spec.

**Comment by Andrei-Popov** [comment]
Fixed in TBPROTO-09.
