### ISSUE TITLE
TBPROTO: TBNEGO: Clarifying Token Binding behavior with renegotiation

### ISSUE THREAD

**Issue by equalsJeffH** [TokenBinding/Internet-Drafts#73]
See thread wrt "Clarifying Token Binding behavior with renegotiation" beginning here..

https://www.ietf.org/mail-archive/web/unbearable/current/msg00907.html

See also PR #72

**Comment by Andrei-Popov** [comment]
Clarified in TBPROTO-11 and TBNEGO-6
