### ISSUE TITLE
TBPROTO: add threat model discussion wrt Token Binding for 0-RTT connections ?

### ISSUE THREAD

**Issue by equalsJeffH** [TokenBinding/Internet-Drafts#74]
see: https://www.ietf.org/mail-archive/web/unbearable/current/msg00884.html

i.e.: "Correct, if the attacker has continuous access to the client machine, and is able to use it as a remote signing oracle, then the attacker can successfully export and use the bound token. Or they could keep running on the client machine without all that trouble. In other words, TB is not protecting the tokens on a machine that is continuously compromised, while it remains compromised"

**Comment by Andrei-Popov** [comment]
This is already discussed in the Security Considerations (7.1) and other sections of TBPROTO. We're protecting from token export and replay from remote machines.
