### ISSUE TITLE
Spell out ABNF for true

### ISSUE THREAD

**Issue by annevk** [TokenBinding/Internet-Drafts#8]
Otherwise it's a case-insensitive match. I assume the intent here is to match CORS?

**Comment by balfanz** [comment]
Tried to address this in 6b852282ba70bff2b0f8a756666714b26e6ac50e. Can you re-open if it's not right?

**Comment by annevk** [comment]
I cannot reopen, but that is not correct. See https://fetch.spec.whatwg.org/#http-new-header-syntax for `%x74.72.75.65` which I think is what you want here.

**Comment by balfanz** [comment]
Ok, how about 0bf316536de641780767ce136845b70404e418c1 ?

**Comment by annevk** [comment]
Yup!
