### ISSUE TITLE
HTTPSTB: TBPROTO: "token binding key" terminology ambiguity.. 

### ISSUE THREAD

**Issue by equalsJeffH** [TokenBinding/Internet-Drafts#87]
..and impedance mismatch...

TBPROTO (-tokbind-protocol) uses "token binding key" to sometimes refer to the TB private key or sometimes to TB key pair

HTTPSTB (-tokbind-https) uses "token binding key" to sometimes refer to a "Token Binding ID" (aka a TB public key), and may use the former phrase in other ways also...

**Comment by balfanz** [comment]
Addressed in https://github.com/TokenBinding/Internet-Drafts/pull/92.

**Comment by equalsJeffH** [comment]
Just for completeness sake, PR #92 addressed this for HTTPSTB, but not TBPROTO
