### ISSUE TITLE
HTTPSTB:  TODO remains wrt specifying sec-token-binding header field behavior

### ISSUE THREAD

**Issue by equalsJeffH** [TokenBinding/Internet-Drafts#88]
this TODO remains in HTTPSTB
> [[TODO: possibly add further considerations wrt the behavior of the above header fields, per <https://tools.ietf.org/html/rfc7231#section-8.3>]] 

In glancing at the bullet list at the end of https://tools.ietf.org/html/rfc7231#section-8.3.1  we don't address the first item (and we should), and may arguably need to address others.

**Comment by balfanz** [comment]
addressed in https://github.com/TokenBinding/Internet-Drafts/pull/94
