### ISSUE TITLE
Reconcile interactions between TBNEGO and TLS 1.3

### ISSUE THREAD

**Issue by nharper** [TokenBinding/Internet-Drafts#98]
(from https://mailarchive.ietf.org/arch/msg/unbearable/iA18qpvoIlFo9umezrC_Bhjk57M)

TLS 1.3 specifies that "Future extensions MUST define their interaction with 0-RTT."

I see two potential options to reconcile this disagreement:

1) Have TBNEGO specify something like "Token Binding and 0-RTT MUST NOT both be negotiated on the same connection" and let draft-ietf-tokbind-tls13-0rtt update TBNEGO later.
2) Specify in TBNEGO a max TLS version of 1.2, and have draft-ietf-tokbind-tls13-0rtt or another draft specify the behavior of the extension in TLS 1.3 and higher.

**Comment by Andrei-Popov** [comment]
Fixed in TBNEGO-08.
